@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzI4NzY4NTJ9.q9HTVPrMm-yvE4QvzEz66YFHqxH5XPCAYVxOihPNsFo
# Authorization: Bearer {{jwt}}


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "evan@test.com",
  "password": "password"
}

### Datalogs Index
GET http://localhost:3000/datalogs.json